// Copyright Nightfall Relay. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "NightfallSkyProfile.generated.h"

class UTexture;

/**
 * One authored lighting state. Four of these describe the whole cycle and the director
 * blends between them by solar altitude, so the entire look of the slice is data.
 */
USTRUCT(BlueprintType)
struct NIGHTFALL_API FNightfallSkyKey
{
	GENERATED_BODY()

	/** Sun brightness in lux. Physical units, because the atmosphere expects them. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sun")
	float SunIntensityLux = 60000.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sun")
	FLinearColor SunColor = FLinearColor(1.0f, 0.95f, 0.86f);

	/** Angular diameter of the sun disc. Widening it at dusk softens every shadow at once. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sun", meta = (ClampMin = "0.0", ClampMax = "12.0"))
	float SunSourceAngleDegrees = 0.5357f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sun", meta = (ClampMin = "0.0"))
	float SunVolumetricScattering = 1.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sun")
	bool bSunLightShaftBloom = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sun", meta = (ClampMin = "0.0"))
	float SunLightShaftBloomScale = 0.2f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Moon")
	float MoonIntensityLux = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Moon")
	FLinearColor MoonColor = FLinearColor(0.55f, 0.68f, 1.0f);

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sky Light", meta = (ClampMin = "0.0"))
	float SkyLightIntensity = 1.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sky Light")
	FLinearColor SkyLightColor = FLinearColor::White;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sky Light", meta = (ClampMin = "0.0"))
	float SkyLightVolumetricScattering = 1.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fog", meta = (ClampMin = "0.0"))
	float FogDensity = 0.02f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fog", meta = (ClampMin = "0.0"))
	float FogHeightFalloff = 0.2f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fog")
	FLinearColor FogInscatteringColor = FLinearColor(0.05f, 0.07f, 0.11f);

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fog", meta = (ClampMin = "0.0"))
	float VolumetricFogExtinctionScale = 1.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fog")
	FLinearColor VolumetricFogAlbedo = FLinearColor::White;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fog")
	FLinearColor VolumetricFogEmissive = FLinearColor::Black;

	/** Mie phase g. Pushing it positive throws the light forward into shafts. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fog", meta = (ClampMin = "-0.9", ClampMax = "0.9"))
	float VolumetricFogScatteringDistribution = 0.2f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Grading", meta = (ClampMin = "-8.0", ClampMax = "8.0"))
	float ExposureBias = 0.0f;

	/** Linear blend between two authored keys. */
	static FNightfallSkyKey Blend(const FNightfallSkyKey& A, const FNightfallSkyKey& B, float Alpha);
};

/**
 * The complete authored day/night look, as four keys plus the grade applied on top.
 *
 * Generated by the content builder and editable in the editor. ANightfallSkyDirector holds
 * a reference and evaluates it every frame.
 */
UCLASS(BlueprintType)
class NIGHTFALL_API UNightfallSkyProfile : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	UNightfallSkyProfile();

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Keys")
	FNightfallSkyKey Night;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Keys")
	FNightfallSkyKey Dawn;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Keys")
	FNightfallSkyKey Day;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Keys")
	FNightfallSkyKey Dusk;

	/** Solar altitude in degrees at or below which the Night key applies outright. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Blend")
	float NightAltitudeDegrees = -6.0f;

	/** Solar altitude in degrees at or above which the Day key applies outright. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Blend")
	float DayAltitudeDegrees = 10.0f;

	/** Colour grading LUT applied by the director's post process volume. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Grading")
	TObjectPtr<UTexture> ColorGradingLUT;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Grading", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float ColorGradingIntensity = 1.0f;

	/** Blend the four keys down to the state for a given solar altitude. */
	UFUNCTION(BlueprintCallable, Category = "Nightfall|Sky")
	FNightfallSkyKey Evaluate(float SunAltitudeDegrees, bool bMorning) const;
};
