"""Shared helpers for the Nightfall content build.

Everything in the project's Content folder is generated by these scripts running inside a
headless editor. Nothing is hand-placed and nothing comes from a marketplace, so a fresh
clone can rebuild the entire world from source with one command.
"""

import unreal

LOG = unreal.log
WARN = unreal.log_warning
ERROR = unreal.log_error

ROOT = "/Game/Nightfall"

PATHS = {
    "materials": ROOT + "/Materials",
    "meshes": ROOT + "/Meshes",
    "data": ROOT + "/Data",
    "input": ROOT + "/Input",
    "maps": ROOT + "/Maps",
    "pcg": ROOT + "/PCG",
    "textures": ROOT + "/Textures",
}

_asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
_asset_lib = unreal.EditorAssetLibrary


def banner(text):
    LOG("")
    LOG("=" * 78)
    LOG("  " + text)
    LOG("=" * 78)


def ensure_directories():
    for path in PATHS.values():
        if not _asset_lib.does_directory_exist(path):
            _asset_lib.make_directory(path)


#: Content roots this build writes to. Plugin mounts are not scanned at editor startup
#: when their feature failed to register, so the registry has to be told about them or
#: does_asset_exist lies and the build tries to create over a file that is already there.
CONTENT_ROOTS = [ROOT, "/GridRestoration", "/SurveyScanner"]


def scan_content_roots():
    registry = unreal.AssetRegistryHelpers.get_asset_registry()
    existing = [p for p in CONTENT_ROOTS if _asset_lib.does_directory_exist(p)]
    if existing:
        registry.scan_paths_synchronous(existing, force_rescan=True)


def asset_path(folder_key, name):
    return "%s/%s" % (PATHS[folder_key], name)


def exists(folder_key, name):
    return _asset_lib.does_asset_exist(asset_path(folder_key, name))


def load(folder_key, name):
    """Load an asset this build produced, or None."""
    path = asset_path(folder_key, name)
    return _asset_lib.load_asset(path) if _asset_lib.does_asset_exist(path) else None


def create(folder_key, name, asset_class, factory=None):
    """Create or reuse an asset of a given class.

    Reusing an existing asset of the right class rather than deleting and recreating it is
    deliberate. A package created earlier in the same editor session stays referenced after
    a delete, and AssetTools then refuses to create over it - which turns a second run of
    the build into a failure. Every caller assigns all of the properties it cares about, so
    reuse converges on the same result.
    """
    path = asset_path(folder_key, name)

    if _asset_lib.does_asset_exist(path):
        existing = _asset_lib.load_asset(path)
        if existing is not None and existing.get_class() == asset_class.static_class():
            return existing

        # Wrong class in the way: drop it, and collect so the package name frees up.
        _asset_lib.delete_asset(path)
        unreal.SystemLibrary.collect_garbage()

    asset = _asset_tools.create_asset(name, PATHS[folder_key], asset_class, factory)
    if asset is None:
        ERROR("failed to create %s" % path)
    return asset


def create_at(package_path, name, asset_class, factory=None):
    """Create or reuse an asset at an arbitrary mount point, such as a plugin's content."""
    path = "%s/%s" % (package_path, name)

    if not _asset_lib.does_directory_exist(package_path):
        _asset_lib.make_directory(package_path)

    if _asset_lib.does_asset_exist(path):
        existing = _asset_lib.load_asset(path)
        if existing is not None and existing.get_class() == asset_class.static_class():
            return existing
        _asset_lib.delete_asset(path)
        unreal.SystemLibrary.collect_garbage()

    asset = _asset_tools.create_asset(name, package_path, asset_class, factory)
    if asset is None:
        ERROR("failed to create %s" % path)
    return asset


def save(asset):
    """Save one asset by object reference."""
    if asset is None:
        return False
    return _asset_lib.save_loaded_asset(asset, only_if_is_dirty=False)


def save_all():
    """Flush everything under the project's content root."""
    for path in PATHS.values():
        if _asset_lib.does_directory_exist(path):
            _asset_lib.save_directory(path, only_if_is_dirty=False, recursive=True)


def linear(r, g, b, a=1.0):
    return unreal.LinearColor(r, g, b, a)


def vec(x=0.0, y=0.0, z=0.0):
    return unreal.Vector(x, y, z)


def rot(pitch=0.0, yaw=0.0, roll=0.0):
    """Build an FRotator by name.

    unreal.Rotator's positional order is (roll, pitch, yaw), which is not the order the
    engine prints them in and not the order anyone expects. Always pass by keyword.
    """
    return unreal.Rotator(roll=roll, pitch=pitch, yaw=yaw)


def xform(location=None, rotation=None, scale=None):
    return unreal.Transform(
        location if location is not None else vec(),
        rotation if rotation is not None else rot(),
        scale if scale is not None else vec(1.0, 1.0, 1.0),
    )
